apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserver2 
  template:
    metadata:
      labels:
        app: authserver2
    spec:
      containers:
      - name: authserver2 
        image: rolfeiacr.azurecr.io/authserver:v2.4
        ports:
        - containerPort: 3001
      imagePullSecrets:
      - name: my-acr-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: authserver2
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: authserver2 
